### ISSUE TITLE
Potential bug with '--' location codes in handler. HTTPServer_RequestHandler.fetch_index_rows

### ISSUE THREAD

**Issue by nick-falco** [EarthScope/portable-fdsnws-dataselect#26]
I believe the following statement will throw a `ValueError: 'tuple' object does not support item assignment`, since tuples are immutable.

```
# Replace "--" location ID request alias with true empty value
if req[2] == "--":
    req[2] = ""
```

https://github.com/iris-edu/portable-fdsnws-dataselect/blob/master/portable_fdsnws_dataselect/handler.py#L323-L325

**Comment by chad-earthscope** [comment]
The values are mutable, confirmed with run time test.  I didn't roll back to see why...
